USE [BookRentalDetails]
GO

/****** Object:  Table [dbo].[GenderInfo]    Script Date: 4/11/2022 11:38:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GenderInfo](
	[Gender_ID] [int] NOT NULL,
	[Gender] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_GenderInfo] PRIMARY KEY CLUSTERED 
(
	[Gender_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


